### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Skrtono** [XPixelGroup/BasicSR#571]
pip install basicsr
Collecting basicsr
  Downloading basicsr-1.4.2.tar.gz (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.5/172.5 kB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Skrtono\AppData\Local\Temp\pip-install-whhdt2x7\basicsr_4be42d624f1e4adbb7280938a67410f2\setup.py", line 147, in <module>
          setup(
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\wheel.py", line 96, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\wheel.py", line 104, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\wheel.py", line 125, in _convert_metadata
          _unpack_zipfile_obj(zf, destination_eggdir)
        File "C:\Users\Skrtono\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\archive_util.py", line 129, in _unpack_zipfile_obj
          with open(target, 'wb') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Skrtono\\AppData\\Local\\Temp\\pip-install-whhdt2x7\\basicsr_4be42d624f1e4adbb7280938a67410f2\\.eggs\\torch-1.12.1-py3.10-win-amd64.egg\\caffe2\\python\\serialized_test\\data\\operator_test\\piecewise_linear_transform_test.test_multi_predictions_params_from_arg.zip'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by HowcanoeWang** [comment]
Got the same problem on Win11 with AMD CPU, but successfully installed on the Intel CPU

```python
(NovelAI) D:\NovelAI\stable-diffusion-webui>pip install basicsr
Collecting basicsr
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\CREST\AppData\Local\Temp\pip-install-96gfd2f6\basicsr_104fd359b28441cfa2d07eebaaae92d7\setup.py", line 147, in <module>
          setup(
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\wheel.py", line 96, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\wheel.py", line 104, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\wheel.py", line 125, in _convert_metadata
          _unpack_zipfile_obj(zf, destination_eggdir)
        File "C:\ProgramData\Miniconda3\envs\NovelAI\lib\site-packages\setuptools\archive_util.py", line 129, in _unpack_zipfile_obj
          with open(target, 'wb') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\CREST\\AppData\\Local\\Temp\\pip-install-96gfd2f6\\basicsr_104fd359b28441cfa2d07eebaaae92d7\\.eggs\\torch-1.12.1-py3.10-win-amd64.egg\\caffe2\\python\\serialized_test\\data\\operator_test\\learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(NovelAI) D:\NovelAI\stable-diffusion-webui>python
Python 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

**Comment by Torala** [comment]
1.Clone the repo
`git clone https://github.com/xinntao/BasicSR.git`
2.Install dependent packages
`cd BasicSR`
`pip install -r requirements.txt`
3.Install BasicSR
Please run the following commands in the BasicSR root path to install BasicSR:
`python setup.py develop`

**Comment by Nuullll** [comment]
Likely due to the file path length limitation (260 characters by default) on windows..

`C:\Users\Skrtono\AppData\Local\Temp\pip-install-whhdt2x7\basicsr_4be42d624f1e4adbb7280938a67410f2\.eggs\torch-1.12.1-py3.10-win-amd64.egg\caffe2\python\serialized_test\data\operator_test\piecewise_linear_transform_test.test_multi_predictions_params_from_arg.zip` --> 261 characters

**Comment by hammadtariq-dh** [comment]
This is what worked for me

1. Clone the repo
```
git clone https://github.com/XPixelGroup/BasicSR.git
```

2. Go to the root directory
```
cd BasicSR
```

3. Go to ```setup.py file``` (line 79) and update the ```get_version()``` method
```
def get_version():
    with open(version_file, 'r') as f:
        exec(compile(f.read(), version_file, 'exec'))
    return "1.4.2"
```

4. Save the file then switch to environment (if not done already)
```
# activate your virtual environment
python -m venv venv

# for mac/unix
source venv/bin/activate

#for windows
venv/Scripts/activate
```

5. Install it from your locally modified folder
```
pip install .
```


This will install the updated package into your current environment.
