### ISSUE TITLE
Training Got Stuck After an Epoch

### ISSUE THREAD

**Issue by zdyshine** [XPixelGroup/BasicSR#582]
Hi, Thanks for your wonderful work.
I'm training with my own dataset. But it just got stuck after one epoch.

Version Information:
        BasicSR: 1.4.2
        PyTorch: 1.12.1+cu113
        TorchVision: 0.13.1+cu113

2022-12-02 00:48:03,899 INFO: [train..][epoch:  0, iter:   3,200, lr:(5.000e-04,)] [eta: 7 days, 4:32:25, time (data): 0.617 (0.008)] l_pix: 2.0122e-02
2022-12-02 00:49:05,723 INFO: [train..][epoch:  0, iter:   3,300, lr:(5.000e-04,)] [eta: 7 days, 4:28:55, time (data): 0.619 (0.007)] l_pix: 1.9322e-02
2022-12-02 00:50:07,599 INFO: [train..][epoch:  0, iter:   3,400, lr:(5.000e-04,)] [eta: 7 days, 4:25:49, time (data): 0.619 (0.009)] l_pix: 2.3699e-02
2022-12-02 00:51:10,569 INFO: [train..][epoch:  0, iter:   3,500, lr:(5.000e-04,)] [eta: 7 days, 4:28:01, time (data): 0.636 (0.012)] l_pix: 1.9436e-02
2022-12-02 00:52:12,115 INFO: [train..][epoch:  0, iter:   3,600, lr:(5.000e-04,)] [eta: 7 days, 4:23:28, time (data): 0.624 (0.010)] l_pix: 2.0423e-02
2022-12-02 00:53:12,679 INFO: [train..][epoch:  0, iter:   3,700, lr:(5.000e-04,)] [eta: 7 days, 4:14:43, time (data): 0.602 (0.007)] l_pix: 1.8931e-02
^[[6~^CTraceback (most recent call last):
  File "basicsr/train.py", line 221, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 160, in train_pipeline
    train_data = prefetcher.next()
  File "/BasicSR/basicsr/data/prefetch_dataloader.py", line 74, in next
    return next(self.loader)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1325, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

It seems to be a multithreading problem, but I don't know how to solve it. Can you give me some suggestions

**Comment by miaosong2000** [comment]
Same, Have you solved this problem?
