### ISSUE TITLE
 model parameters

### ISSUE THREAD

**Issue by Yzs007** [XPixelGroup/BasicSR#588]
How to calculate model parameters in BasicSR？ When I use thop.profile, the following error occurs：

D:\anaconda3\envs\Pytorch\python.exe C:/Users/DELL/Desktop/BSRN-main/para.py
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\BSRN-main\para.py", line 9, in <module>
    flops, params = profile(model, inputs=(input,), verbose=True)
  File "D:\anaconda3\envs\Pytorch\lib\site-packages\thop\profile.py", line 206, in profile
    prev_training_status = model.training
AttributeError: 'dict' object has no attribute 'training'

Process finished with exit code 1

**Comment by Rheazheng** [comment]
Have you solved this problem yet? I am currently experiencing the similar problem.If convenience,could you help me?

**Comment by Yzs007** [comment]
> Have you solved this problem yet? I am currently experiencing the similar problem.If convenience,could you help me?

from torchsummaryX import summary
if __name__=='__main__':
    scale = 4
    input = torch.zeros(1, 3, 1280//scale, 720//scale)
    model = Net(in_chan=3, out_chan=3, dim=64, upscale=scale)
    summary(model, input)

**Comment by Miscorf** [comment]
Have you solved this problem yet? I am currently experiencing the similar problem.If convenience,could you help me?

**Comment by Yzs007** [comment]
> Have you solved this problem yet? I am currently experiencing the similar problem.If convenience,could you help me?

What's your problem？
