### ISSUE TITLE
在test过程中出现了关于val值的问题

### ISSUE THREAD

**Issue by luierlyy** [XPixelGroup/BasicSR#623]
2023-06-01 02:27:22,591 INFO: Loading RCAN model from ./experiments/201_RCANx2_scratch_DIV2K_rand0/models/net_g_300000.pth, with param key: [params].
2023-06-01 02:27:22,675 INFO: Model [SRModel] is created.
2023-06-01 02:27:22,676 INFO: Testing set5...
Traceback (most recent call last):
  File "/BasicSR-master/BasicSR-master/basicsr/test.py", line 46, in <module>
    test_pipeline(root_path)
  File "/BasicSR-master/BasicSR-master/basicsr/test.py", line 41, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
KeyError: 'val'

请问这个是因为什么原因导致的么

**Comment by luierlyy** [comment]
添加了val相关的setting之后就可以了，在测试RCAN时参照模板误以为是文件不需要val的部分了
