### ISSUE TITLE
Error:build wheels for basicsr请看一下报错信息，请问我该如何解决

### ISSUE THREAD

**Issue by zrongl** [XPixelGroup/BasicSR#631]
~XXX:(main) ✗ pip install basicsr==1.4.1
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting basicsr==1.4.1
  Downloading https://mirrors.aliyun.com/pypi/packages/c7/c9/9dda955cc560db80bd7433210a3a8e5fc4676fcd88e64527dc3271feb7d1/basicsr-1.4.1.tar.gz (171 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.6/171.6 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (2.4.0)
Requirement already satisfied: future in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from basicsr==1.4.1) (0.18.2)
Requirement already satisfied: lmdb in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (1.4.1)
Requirement already satisfied: numpy>=1.17 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (1.23.5)
Requirement already satisfied: opencv-python in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (4.8.0.74)
Requirement already satisfied: Pillow in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (10.0.0)
Requirement already satisfied: pyyaml in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (6.0)
Requirement already satisfied: requests in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (2.28.1)
Requirement already satisfied: scikit-image in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (0.21.0)
Requirement already satisfied: scipy in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (1.11.1)
Requirement already satisfied: tb-nightly in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (2.14.0a20230808)
Requirement already satisfied: torch>=1.7 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (2.0.1)
Requirement already satisfied: torchvision in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (0.15.2)
Requirement already satisfied: tqdm in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (4.65.0)
Requirement already satisfied: yapf in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from basicsr==1.4.1) (0.40.1)
Requirement already satisfied: filelock in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from torch>=1.7->basicsr==1.4.1) (3.12.2)
Requirement already satisfied: typing-extensions in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from torch>=1.7->basicsr==1.4.1) (4.5.0)
Requirement already satisfied: sympy in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from torch>=1.7->basicsr==1.4.1) (1.12)
Requirement already satisfied: networkx in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from torch>=1.7->basicsr==1.4.1) (3.1)
Requirement already satisfied: jinja2 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from torch>=1.7->basicsr==1.4.1) (3.1.2)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from requests->basicsr==1.4.1) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from requests->basicsr==1.4.1) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from requests->basicsr==1.4.1) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from requests->basicsr==1.4.1) (2022.9.24)
Requirement already satisfied: imageio>=2.27 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from scikit-image->basicsr==1.4.1) (2.31.1)
Requirement already satisfied: tifffile>=2022.8.12 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from scikit-image->basicsr==1.4.1) (2023.7.18)
Requirement already satisfied: PyWavelets>=1.1.1 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from scikit-image->basicsr==1.4.1) (1.4.1)
Requirement already satisfied: packaging>=21 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from scikit-image->basicsr==1.4.1) (23.1)
Requirement already satisfied: lazy_loader>=0.2 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from scikit-image->basicsr==1.4.1) (0.3)
Requirement already satisfied: absl-py>=0.4 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from tb-nightly->basicsr==1.4.1) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from tb-nightly->basicsr==1.4.1) (1.56.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from tb-nightly->basicsr==1.4.1) (2.21.0)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from tb-nightly->basicsr==1.4.1) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from tb-nightly->basicsr==1.4.1) (3.4.3)
Requirement already satisfied: protobuf>=3.19.6 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from tb-nightly->basicsr==1.4.1) (3.20.3)
Requirement already satisfied: setuptools>=41.0.0 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.1) (58.0.4)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from tb-nightly->basicsr==1.4.1) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from tb-nightly->basicsr==1.4.1) (2.3.6)
Requirement already satisfied: wheel>=0.26 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from tb-nightly->basicsr==1.4.1) (0.37.0)
Requirement already satisfied: importlib-metadata>=6.6.0 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from yapf->basicsr==1.4.1) (6.8.0)
Requirement already satisfied: platformdirs>=3.5.1 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from yapf->basicsr==1.4.1) (3.10.0)
Requirement already satisfied: tomli>=2.0.1 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from yapf->basicsr==1.4.1) (2.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.1) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.1) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.1) (4.9)
Requirement already satisfied: six>=1.9.0 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.1) (1.15.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from google-auth-oauthlib<1.1,>=0.5->tb-nightly->basicsr==1.4.1) (1.3.1)
Requirement already satisfied: zipp>=0.5 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=6.6.0->yapf->basicsr==1.4.1) (3.16.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from werkzeug>=1.0.1->tb-nightly->basicsr==1.4.1) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from sympy->torch>=1.7->basicsr==1.4.1) (1.3.0)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tb-nightly->basicsr==1.4.1) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /Users/ronglei/Library/Python/3.9/lib/python/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tb-nightly->basicsr==1.4.1) (3.2.2)
Building wheels for collected packages: basicsr
  Building wheel for basicsr (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kv/tndfk1_s0pg8yv5wf2qndtnh0000gn/T/pip-install-g8a1o9mm/basicsr_ec71bcd55f58464996c9f1859db04926/setup.py", line 141, in <module>
          setup(
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 95, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
          os.mkdir(destination_eggdir)
      FileExistsError: [Errno 17] File exists: '/private/var/folders/kv/tndfk1_s0pg8yv5wf2qndtnh0000gn/T/pip-install-g8a1o9mm/basicsr_ec71bcd55f58464996c9f1859db04926/.eggs/Cython-3.0.0-py3.9-macosx-10.9-universal2.egg'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for basicsr

**Comment by VladSt90** [comment]
Try this

`pip3 install basicsr  --use-pep517`

**Comment by VladSt90** [comment]
And this

`pip3 install gfpgan --use-pep517`
