### ISSUE TITLE
A type error about the make_grid() function

### ISSUE THREAD

**Issue by Tegcoder** [XPixelGroup/BasicSR#651]
Traceback (most recent call last):
  File "C:\Users\tegco\Desktop\Workspace\VSCode\BasicSR\inference\inference_stylegan2.py", line 70, in <module>
    generate(args, g_ema, device, mean_latent, args.randomize_noise)
  File "C:\Users\tegco\Desktop\Workspace\VSCode\BasicSR\inference\inference_stylegan2.py", line 23, in generate
    utils.save_image(
  File "D:\anaconda3\envs\basicsr\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\basicsr\lib\site-packages\torchvision\utils.py", line 146, in save_image
    grid = make_grid(tensor, **kwargs)
  File "D:\anaconda3\envs\basicsr\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: make_grid() got an unexpected keyword argument 'range'

**Comment by Tegcoder** [comment]
I'm using the latest version of pytorch（2.1.0+cu121）
ChatGPT prompted me to make the following changes to the code:
```
sample = (sample + 1) / 2 # Convert pixel value from [-1, 1] to [0, 1]
utils.save_image(
     sample,
     f'samples/{str(i).zfill(6)}.png',
     nrow=int(math.sqrt(args.sample)),
     normalize=True,
)
```
I don’t know if it affects the reasoning effect

**Comment by liuhao16** [comment]
> I'm using the latest version of pytorch（2.1.0+cu121）我正在使用 pytorch 的最新版本（2.1.0+cu121） ChatGPT prompted me to make the following changes to the code:ChatGPT 提醒我对以下代码进行以下更改：
> 
> ```
> sample = (sample + 1) / 2 # Convert pixel value from [-1, 1] to [0, 1]
> utils.save_image(
>      sample,
>      f'samples/{str(i).zfill(6)}.png',
>      nrow=int(math.sqrt(args.sample)),
>      normalize=True,
> )
> ```
> 
> I don’t know if it affects the reasoning effect我不知道这会不会影响推理效果

我按照你的改了 会报错
`/home/xx/anaconda3/envs/SwinIR/lib/python3.11/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/home/xx/anaconda3/envs/SwinIR/lib/python3.11/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/home/xx/anaconda3/envs/SwinIR/lib/python3.11/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/home/xx/project/BasicSR/inference/inference_stylegan2.py:66: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.ckpt)['params_ema']
`
