### ISSUE TITLE
Google Colab Unespected Error

### ISSUE THREAD

**Issue by toux92** [XPixelGroup/BasicSR#671]
just opened the colab version after some months and I got this when start inference:

Traceback (most recent call last):
  File "/content/Real-ESRGAN/inference_realesrgan_video.py", line 10, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

I also found this:

Fix #533 functional_tensor not found

The torchvision.transforms.functional_tensor module is deprecated since torchvision 0.15, and it will be no longer available in 0.17

Change import source of rgb_to_grayscale from torchvision.transforms.functional_tensor to torchvision.transforms.functional, so as to avoid the deprecation warning
----
Since I'm using Real Esrgan on Colab I can't find "degradation.py" so I don't know how to solve this problem (assuming that this will solve the problem).

**Comment by 14790897** [comment]
I released a fixed version to address this issue. Use `pip install basicsr-fixed` instead of `pip install basicsr`.
