### ISSUE TITLE
raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")

### ISSUE THREAD

**Issue by nianliu26** [XPixelGroup/BasicSR#683]
1. 正确安装basicsr，并正常运行过的项目，中间有一天没跑该项目，再跑又会报这个错误，并且我确定已经再类名上正确添加注册类的python注解，类所在文件也是以_model.py结尾。
Traceback (most recent call last):
  File "/mnt/hdd1/denghui/DNN/myReal-ESRGAN/realesrgan/train.py", line 14, in <module>
    train_pipeline(root_path)
  File "/mnt/hdd1/denghui/anaconda3/envs/pytorch/lib/python3.11/site-packages/basicsr/train.py", line 124, in train_pipeline
    model = build_model(opt)
            ^^^^^^^^^^^^^^^^
  File "/mnt/hdd1/denghui/anaconda3/envs/pytorch/lib/python3.11/site-packages/basicsr/models/__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd1/denghui/anaconda3/envs/pytorch/lib/python3.11/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'MedicalSR' found in 'model' registry!"
2. im2tensor函数，似乎没有处理单通道灰度图片输入的能力，需要开发者自己对相关情况进行一定的处理（如：在imfrombytes函数中对flag参数设置为灰度图，再将出结果的维度进行扩展），这似乎与此框架开发初衷相悖

**Comment by Closerpan111** [comment]
你好，请问你解决了读一个问题吗

**Comment by iswangyifan** [comment]
我也遇到同样的问题

**Comment by nianliu26** [comment]
> 我也遇到同样的问题

三方库不同的安装方式会有不同的效果，平常直接pip install <包名>或者用打包的setup.py进行安装的话会将库安装到环境的库目录里面，这个时候如果你要修改代码只能去那个目录里改，而你直接改你下载的代码是无效的。所以平常我们要做二次开发的话建议使用pip install -e .进行安装，这个命令是在环境的库目录里创建一个映射，会将当前目录视为库，此时在当前目录下修改的代码会直接生效

**Comment by YAN287-hub** [comment]
> 1. 安装正确的basicsr，并正常运行过的项目，中间有一天没跑该项目，再跑又会报这个错误，而且我确定已经再类名上添加正确注册类的python注解，类所在文件也是以_model.py结尾。
>    回溯（最近一次调用最后）：
>    文件“/mnt/hdd1/denghui/DNN/myReal-ESRGAN/realesrgan/train.py”，第14行，在
>    train_pipeline（root_path）
>    文件中“/mnt/hdd1/denghui/anaconda3/envs/pytorch/lib/python3.11/site-packages/basicsr/train.py”，第 124 行，在 train_pipeline 
>    model = build_model(opt) 
>    ^^^^^^^^^^^^^^^^^
>    文件中“/mnt/hdd1/denghui/anaconda3/envs/pytorch/lib/python3.11/site-packages/basicsr/models/ **init** .py”，第 26 行，在 build_model 中
>    model = MODEL_REGISTRY.get(opt['model_type'])(opt) 
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    文件“/mnt/hdd1/denghui/anaconda3/envs/pytorch/lib/python3.11/site-packages/basicsr/utils/registry.py”，第 71 行，在 get 中
>    raise KeyError(f"在“{self._name}”注册表中找不到名为“{name}”的对象！") 
>    KeyError: "在“model”注册表中找不到名为“MedicalSR”的对象！"
> 2. im2tensor函数，似乎没有处理单通道灰度图像输入的能力，需要开发者自己对相关情况进行的处理（如：在imfrombytes函数中对标志参数设置为灰度图，再将出结果的维度进行扩展），这似乎与此框架开发初衷相悖

请问，我也是按这种方式读入单通道数据集，训练会不会有什么影响呢
