### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by jasuriy** [XPixelGroup/BasicSR#698]
Hi
I am trying to run inference but getting this error: 
can you please help me fix it? thank you in advance 

command: # inference
!python inference/inference_dfdnet.py --upscale_factor 1 --test_path datasets/upload/ --official_adaption True

Traceback (most recent call last):
  File "/content/BasicSR/inference/inference_dfdnet.py", line 114, in <module>
    net = DFDNet(64, dict_path=args.dict_path).to(device)
  File "/content/BasicSR/basicsr/archs/dfdnet_arch.py", line 77, in __init__
    self.dict = torch.load(dict_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by thd-ux** [comment]
When I inference with inference/inference_basicvsr.py, the input and output results look the same, only the resolution is different. Do you have this problem?

**Comment by jasuriy** [comment]
I could not even get this far. Please let me know if you can solve this
problem.
