### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by 123kaya** [XPixelGroup/BasicSR#711]
I have checked every requested packages，the packages are fine, while the problem still exit.

the following is detail:

python inference_realesrgan.py -n RealESRGAN_x4plus -i inputs --face_enhance
Traceback (most recent call last):
  File "/home/djw/Python/real_esrgen/Real-ESRGAN/inference_realesrgan.py", line 5, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "/home/djw/Python/conda3/envs/myenv/lib/python3.12/site-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/home/djw/Python/conda3/envs/myenv/lib/python3.12/site-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/djw/Python/conda3/envs/myenv/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/djw/Python/conda3/envs/myenv/lib/python3.12/site-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/home/djw/Python/conda3/envs/myenv/lib/python3.12/site-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

**Comment by zq981604786** [comment]
https://blog.csdn.net/2301_79442295/article/details/142788495

**Comment by 14790897** [comment]
I released a fixed version to address this issue. Use `pip install basicsr-fixed` instead of `pip install basicsr`.

**Comment by talzahr** [comment]
As per https://github.com/Daethyra/FreeStream/issues/64 this can be "hacky" fix by editing _../lib/site-packages/basicsr/data/degradations.py_ and modifying the import to be: `from torchvision.transforms.functional import rgb_to_grayscale`

@14790897 's method is easier though since he fixes that for you. 

This was fixed in https://github.com/XPixelGroup/BasicSR/pull/650 However, there is still no stable release with the fix.
